# Generated by Django 5.1.2 on 2024-10-15 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_repara_cidadao", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuarios",
            new_name="Usuario",
        ),
    ]
