# Generated by Django 5.1.2 on 2024-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_repara_cidadao", "0002_rename_usuarios_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="idade",
        ),
        migrations.AddField(
            model_name="usuario",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cep",
            field=models.CharField(
                blank=True, default="00000-000", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cidade",
            field=models.CharField(
                blank=True, default="Sorocaba", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="complemento",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="estado",
            field=models.CharField(default="São Paulo", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="numero",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="referencia",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rua",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="sobrenome",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
