# Generated by Django 5.1.2 on 2024-10-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_repara_cidadao",
            "0003_remove_usuario_idade_usuario_bairro_usuario_cep_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Reparo",
            fields=[
                ("id_reparo", models.AutoField(primary_key=True, serialize=False)),
                ("reparo", models.CharField(max_length=255)),
                ("rua", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cidade",
                    models.CharField(
                        blank=True, default="Sorocaba", max_length=100, null=True
                    ),
                ),
                ("estado", models.CharField(default="São Paulo", max_length=100)),
                (
                    "cep",
                    models.CharField(
                        blank=True, default="00000-000", max_length=10, null=True
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cep",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
